Feature/add new warikan
inoue723/warikan-app pull request #20
Opened 2019-10-20 13:08 UTC by harryshioristyles

下記を追加しました。マージお願いしますう。
・カンマ区切り
・issue #15 支払った日付けを入力できるようにする

2019-10-22 03:00 UTC, inoue723 requested changes

2019-10-22 03:00 UTC, inoue723 commented on src/components/costs/CostList.js
> +              <th>入力日</th>
入力日はいらないので消してください

2019-10-22 03:00 UTC, inoue723 commented on src/components/costs/SaveCost.js
> +    date: "",
dateだけだとなんの日付かわからないので変数名を変えてください

2019-10-22 03:00 UTC, inoue723 commented on src/components/costs/SaveCost.js
> +    }
ここは何をしていますか？
if (this.state.date.length > 0)の方に入ることありますか？
初期値を設定したいときは、8行目のところで定義してください。

2019-10-22 03:12 UTC, inoue723 commented on src/components/costs/CostList.js
> +              <th>入力日</th>
concatCost()という関数はcreatedAtでソートしているので、支払日でソートするよう変更してください

2019-10-22 04:01 UTC, harryshioristyles commented
＜前回追加内容＞
・カンマ区切り
・issue #15 支払った日付けを入力できるようにする

＜今回追加/修正内容＞
・入力日を削除
・変数名をdate => payment_dateに変更
・payment_dateの初期値の設定箇所を変更
・支払日でソートするように変更

以上、マージお願いしますう。

2019-10-22 04:38 UTC, harryshioristyles commented
＜前々回追加内容＞
・カンマ区切り
・issue #15 支払った日付けを入力できるようにする

＜前回追加/修正内容＞
・入力日を削除
・変数名をdate => payment_dateに変更
・payment_dateの初期値の設定箇所を変更
・支払日でソートするように変更

＜今回追加/修正内容＞
・変数名payment_dateをキャメルケースpaymentDateに変更
・momentを使用する

以上、マージお願いしますう。

2019-10-24 15:16 UTC, inoue723 requested changes
@harryshioristyles 
いい感じ！
あと少しだけ修正お願い！

2019-10-24 15:16 UTC, inoue723 commented on src/components/costs/CostList.js
> +    costs.sort((a, b) => b.paymentDate.toDate() - a.paymentDate.toDate());
paymentDateがない場合エラーになる・・・
既存のpaymentDateがないレコードにpaymentDateを追加してもいいかも

2019-10-24 15:16 UTC, inoue723 commented on src/components/costs/CostList.js
>                {/* TODO: 支払日は今のところcreatedAtを見てるので、カラムを作って、記録するときに入力できるようにする */}
コメントは削除よろしく＾ー＾

2019-10-24 15:16 UTC, inoue723 commented on src/components/costs/CostList.js
> +    costs.sort((a, b) => b.paymentDate.toDate() - a.paymentDate.toDate());
@harryshioristyles 
createdAtをそのままpaymentDateにするとか

2019-10-25 16:50 UTC, inoue723 approved these changes

2019-10-25 16:52 UTC, merged